DELETE http://localhost:3003/api/blogs/6536fc54185d34a293c420cd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NTM1NDA5ZTFlZTI3YjBiMWJkODM0MzEiLCJpYXQiOjE2OTgxMDA5NjcsImV4cCI6MTY5ODcwNTc2N30.E_y9GAQZ1ZoC3blpK5gVMIRwtXMqH8QyLcawnlv8I9Q