POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testing with Jest",
  "author": "6535409e1ee27b0b1bd83431",
  "url": "https://testing-with-jest.com",
  "likes": 25
}